[package]
name = "tcp-kcp-wrapper"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.11.0"
clap = { version = "4.5.54", features = ["derive"] }
kcp-rs = "0.2.4"
tokio = { version = "1.49.0", features = ["full"]}
