[package]
name = "tcp-kcp-wrapper"
version = "1.0.4"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
bytes = "1.11.0"
clap = { version = "4.5.54", features = ["derive"] }
kcp-rs = "0.2.4"
tokio = { version = "1.49.0", features = ["full"] }
uuid = { version = "1.19.0", features = ["v4"] }
